export default [
    {
        "id": 1,
        "first": "Gale",
        "last": "Mcmyne",
        "age": 16,
        "state": "RI"
    }, {
        "id": 2,
        "first": "Tighe",
        "last": "Walls",
        "age": 43,
        "state": "AL"
    }, {
        "id": 3,
        "first": "Anuj",
        "last": "Wittcop",
        "age": 16,
        "state": "MO"
    }, {
        "id": 4,
        "first": "Elisha",
        "last": "Mahan",
        "age": 28,
        "state": "MA"
    }, {
        "id": 5,
        "first": "Sutman",
        "last": "Kiab",
        "age": 18,
        "state": "ME"
    }, {
        "id": 6,
        "first": "Wazir",
        "last": "Odonoghue",
        "age": 27,
        "state": "ND"
    }, {
        "id": 7,
        "first": "Renardo",
        "last": "Schuessler",
        "age": 5,
        "state": "OK"
    }, {
        "id": 8,
        "first": "Colleen",
        "last": "Schotuen",
        "age": 33,
        "state": "DE"
    }, {
        "id": 9,
        "first": "Natalia",
        "last": "Sacks",
        "age": 24,
        "state": "FL"
    }, {
        "id": 10,
        "first": "Kamaniee",
        "last": "Knaus",
        "age": 11,
        "state": "ID"
    }, {
        "id": 11,
        "first": "Deena",
        "last": "Downing",
        "age": 39,
        "state": "NM"
    }, {
        "id": 12,
        "first": "Gueorgui",
        "last": "Downing",
        "age": 22,
        "state": "LA"
    }, {
    "id": 13,
        "first": "Toya",
        "last": "Wallace",
        "age": 19,
        "state": "MD"
    }, {
        "id": 14,
        "first": "Deborah",
        "last": "Morrison",
        "age": 14,
        "state": "VT"
    }, {
    "id": 15,
        "first": "Nerissa",
        "last": "Wade",
        "age": 7,
        "state": "DE"
    }, {
        "id": 16,
        "first": "Glenn",
        "last": "Bommi",
        "age": 8,
        "state": "MO"
    }, {
        "id": 17,
        "first": "Kate",
        "last": "Azcunaga",
        "age": 25,
        "state": "ME"
    }, {
        "id": 18,
        "first": "Jesse",
        "last": "Ingham",
        "age": 50,
        "state": "OK"
    }, {
        "id": 19,
        "first": "Gateri",
        "last": "Sergent",
        "age": 50,
        "state": "MA"
    }, {
        "id": 20,
        "first": "Marian",
        "last": "Malmfeldt",
        "age": 50,
        "state": "DC"
    }, {
        "id": 21,
        "first": "Marian A",
        "last": "Malmfeldt",
        "age": 51,
        "state": "DC"
    }];